apiVersion: shrine/v1
kind: Resource
metadata:
  name: events-db
  owner: aura
spec:
  type: mariadb
  version: "11"
  image: mariadb:11
  port: 3306
  outputs:
    - name: host
    - name: port
    - name: MARIADB_DATABASE
      value: "events"
    - name: MARIADB_USER
      value: "aura_user"
    - name: MARIADB_PASSWORD
      generated: true
    - name: MARIADB_ROOT_PASSWORD
      generated: true
  volumes:
    - name: data
      mountPath: /var/lib/mysql
